name: Google Search Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  google-search:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl
        wget -q https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.60/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip -d chrome
        sudo mv chrome/chrome-linux64 /usr/local/share/
        sudo ln -s /usr/local/share/chrome-linux64/chrome /usr/local/bin/google-chrome
        sudo apt-get -f install -y

    - name: Install ChromeDriver
      run: |
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.60/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip -d chromedriver
        sudo mv chromedriver/chromedriver-linux64 /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install OpenFortiVPN
      run: sudo apt-get install -y openfortivpn

    - name: Configure and Start VPN
      env:
        VPN_HOST: ${{ secrets.VPN_HOST }}
        VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      run: |
        sudo openfortivpn $VPN_HOST:443 --username=$VPN_USERNAME --password=$VPN_PASSWORD &
        sleep 10  # Wait for VPN to establish connection

    - name: Run Google search script
      run: python google_search.py
